<?php



$this->translate("index");

$this->translate("index::index");

$this->translate("store");

$this->translate("store::index");

$this->translate("store::add");

$this->translate("store::edit");

$this->translate("store::details");

$this->translate("store::update-price-list");

$this->translate("store::edit-price-list");

$this->translate("store::change-status");

$this->translate("store::delete");

$this->translate("car-model");

$this->translate("car-model::index");

$this->translate("car-model::add");

$this->translate("car-model::edit");

$this->translate("car-model::change-select");

$this->translate("car-model::delete");

$this->translate("car-equipment");

$this->translate("car-equipment::index");

$this->translate("car-equipment::add");

$this->translate("car-equipment::edit");

$this->translate("car-equipment::delete");

$this->translate("brand");

$this->translate("brand::index");

$this->translate("brand::add");

$this->translate("brand::edit");

$this->translate("brand::change-select");

$this->translate("brand::delete");

$this->translate("city");

$this->translate("city::index");

$this->translate("city::add");

$this->translate("city::edit");

$this->translate("city::delete");

$this->translate("users");

$this->translate("users::index");

$this->translate("users::add");

$this->translate("users::edit");

$this->translate("users::login");

$this->translate("users::logout");

$this->translate("users::forgot-password");

$this->translate("users::change-password");

$this->translate("users::delete");

$this->translate("roles");

$this->translate("roles::index");

$this->translate("roles::add");

$this->translate("roles::edit");

$this->translate("roles::delete");

$this->translate("vidy-rassrochek");

$this->translate("vidy-rassrochek::index");

$this->translate("vidy-rassrochek::add");

$this->translate("vidy-rassrochek::edit");

$this->translate("vidy-rassrochek::delete");

$this->translate("vidy-rassrochek::option");

$this->translate("vidy-kreditov");

$this->translate("vidy-kreditov::index");

$this->translate("vidy-kreditov::add");

$this->translate("vidy-kreditov::edit");

$this->translate("vidy-kreditov::delete");

$this->translate("vidy-kreditov::option");

$this->translate("car-action");

$this->translate("car-action::index");

$this->translate("car-action::add");

$this->translate("car-action::edit");

$this->translate("car-action::delete");

$this->translate("documents");

$this->translate("documents::index");

$this->translate("documents::add");

$this->translate("documents::edit");

$this->translate("documents::view");

$this->translate("documents::history");

$this->translate("documents::delete-file");

$this->translate("documents::delete");

$this->translate("permission");

$this->translate("permission::update-urls");

$this->translate("status");

$this->translate("status::index");

$this->translate("status::add");

$this->translate("status::edit");

$this->translate("status::delete");

$this->translate("mail");

$this->translate("mail::index");

$this->translate("mail::add");

$this->translate("mail::edit");

$this->translate("warranty");

$this->translate("warranty::index");

$this->translate("warranty::add");

$this->translate("warranty::edit");

$this->translate("warranty::history");

$this->translate("warranty::correspondence");

$this->translate("warranty::confirm-warranty");

$this->translate("warranty::send-request");

$this->translate("warranty::reject-warranty");

$this->translate("warranty::performed");

$this->translate("warranty::work-order-index");

$this->translate("warranty::work-order-add");

$this->translate("warranty::work-order-download");

$this->translate("warranty::work-order-edit");

$this->translate("warranty::take-work");

$this->translate("files");

$this->translate("files::delete-file");

$this->translate("logistics");

$this->translate("logistics::application-taken-work");

$this->translate("logistics::edit");

$this->translate("logistics::history");

$this->translate("logistics::order");

$this->translate("logistics::order-download");

$this->translate("logistics::confirm-application");

$this->translate("logistics::take-cars");

$this->translate("settings");

$this->translate("settings::index");

$this->translate("category");

$this->translate("category::index");

$this->translate("category::add");

$this->translate("category::edit");

$this->translate("logistics::add-stage");

$this->translate("logistics::add-car");

$this->translate("car-subgroup");

$this->translate("car-subgroup::index");

$this->translate("car-subgroup::add");

$this->translate("car-subgroup::edit");

$this->translate("car-subgroup::delete");

$this->translate("warranty::response-request");

$this->translate("logistics::application-rejected");

$this->translate("category::delete");

$this->translate("brand-setting");

$this->translate("brand-setting::closed-period");

$this->translate("vidy-lizinga");

$this->translate("vidy-lizinga::index");

$this->translate("vidy-lizinga::add");

$this->translate("vidy-lizinga::edit");

$this->translate("vidy-lizinga::delete");

$this->translate("vidy-lizinga::option");

$this->translate("logistics::download");

$this->translate("store::delete-selectedItems");

$this->translate("users::monitoring");

$this->translate("logistics::history-one-car");

$this->translate("rod-zanyatiy-sfera-deyatelnosti");

$this->translate("rod-zanyatiy-sfera-deyatelnosti::index");

$this->translate("rod-zanyatiy-sfera-deyatelnosti::add");

$this->translate("rod-zanyatiy-sfera-deyatelnosti::edit");

$this->translate("rod-zanyatiy-sfera-deyatelnosti::delete");

$this->translate("rod-zanyatiy-sfera-deyatelnosti::option");

$this->translate("sfera-ispolzovaniya-avtomobilya");

$this->translate("sfera-ispolzovaniya-avtomobilya::index");

$this->translate("sfera-ispolzovaniya-avtomobilya::add");

$this->translate("sfera-ispolzovaniya-avtomobilya::edit");

$this->translate("sfera-ispolzovaniya-avtomobilya::delete");

$this->translate("sfera-ispolzovaniya-avtomobilya::option");

$this->translate("store::change-item");

$this->translate("warranty::download");

$this->translate("warranty::delete");

$this->translate("logistics::orders");

$this->translate("logistics::delete");

$this->translate("store::control-sales");

$this->translate("store::control-car");

$this->translate("store::history");

$this->translate("store::dealer-discount");

$this->translate("store::mail-history");

$this->translate("documents::mail-history");

$this->translate("warranty::mail-history");

$this->translate("logistics::mail-history");

$this->translate("supplier");

$this->translate("supplier::index");

$this->translate("supplier::add");

$this->translate("supplier::edit");

$this->translate("supplier::delete");

$this->translate("sphinx");

$this->translate("sphinx::indexer");

$this->translate("buyers");

$this->translate("buyers::index");

$this->translate("buyers::add");

$this->translate("buyers::edit");

$this->translate("buyers::delete");

$this->translate("file-upload");

$this->translate("file-upload::index");

$this->translate("optional-equipment");

$this->translate("optional-equipment::index");

$this->translate("optional-equipment::add");

$this->translate("optional-equipment::edit");

$this->translate("optional-equipment::delete");

$this->translate("store::optional-equipment");

$this->translate("store::add-to-car-optional-equipment");

$this->translate("store::delete-optional-equipment");

$this->translate("users::generate-passwords");

$this->translate("vidy-oplat");

$this->translate("vidy-oplat::index");

$this->translate("vidy-oplat::add");

$this->translate("vidy-oplat::edit");

$this->translate("vidy-oplat::delete");

$this->translate("vidy-oplat::option");

$this->translate("dealerships");

$this->translate("dealerships::index");

$this->translate("dealerships::add");

$this->translate("dealerships::edit");

$this->translate("dealerships::delete");

$this->translate("regions");

$this->translate("regions::index");

$this->translate("regions::add");

$this->translate("regions::edit");

$this->translate("regions::delete");

$this->translate("buyers::details");

$this->translate("towns");

$this->translate("towns::index");

$this->translate("towns::add");

$this->translate("towns::edit");

$this->translate("towns::delete");

$this->translate("regions::change-select");

$this->translate("store::filters-all");

$this->translate("store::import");

$this->translate("store::export");

$this->translate("store::export-all");

$this->translate("car-assembly");

$this->translate("car-assembly::index");

$this->translate("car-assembly::add");

$this->translate("car-assembly::edit");

$this->translate("car-assembly::delete");

$this->translate("order-sale");

$this->translate("order-sale::index");

$this->translate("order-sale::add");

$this->translate("order-sale::edit");

$this->translate("order-sale::payment");

$this->translate("order-sale::documents");

$this->translate("order-sale::add-car");

$this->translate("order-sale::issue-order-sale");

$this->translate("order-sale::delete-order-sale-store");

$this->translate("order-sale::history");

$this->translate("order-sale::delete-order-sale-paid");

$this->translate("order-sale::create-document");

$this->translate("order-sale::export");

$this->translate("cron");

$this->translate("cron::cron");

$this->translate("reminder");

$this->translate("car-detail-defect");

$this->translate("car-detail-defect::index");

$this->translate("car-detail-defect::edit");

$this->translate("car-detail-defect::export");

$this->translate("files::delete-created-file");

$this->translate("staff");

$this->translate("staff::index");

$this->translate("staff::edit");

$this->translate("department");

$this->translate("department::index");

$this->translate("department::add");

$this->translate("department::edit");

$this->translate("department::delete");

$this->translate("order-sale::order-document");

$this->translate("authorized-persons");

$this->translate("authorized-persons::index");

$this->translate("authorized-persons::add");

$this->translate("authorized-persons::edit");

$this->translate("authorized-persons::delete");

$this->translate("staff::delete");

$this->translate("users::history");

$this->translate("job-titles");

$this->translate("job-titles::index");

$this->translate("job-titles::add");

$this->translate("job-titles::edit");

$this->translate("job-titles::delete");

$this->translate("clients");

$this->translate("clients::index");

$this->translate("clients::add");

$this->translate("clients::edit");

$this->translate("clients::delete");

$this->translate("clients::export");

$this->translate("autocarts");

$this->translate("autocarts::index");

$this->translate("autocarts::add");

$this->translate("autocarts::edit");

$this->translate("autocarts::delete");

$this->translate("logistics::documents");

$this->translate("logistics::create-document");

$this->translate("clients::processed");

$this->translate("store::refresh-price-list");

$this->translate("customer-response");

$this->translate("customer-response::index");

$this->translate("customer-response::add");

$this->translate("customer-response::edit");

$this->translate("customer-response::delete");

$this->translate("call-center");

$this->translate("call-center::index");

$this->translate("call-center::edit");

$this->translate("call-center::import");

$this->translate("call-center::export");

$this->translate("users::delete-file");

$this->translate("staff::delete-file");

$this->translate("call-center::delete");

$this->translate("store::our-accessories");

$this->translate("store::delete-our-accessories");

$this->translate("spares");

$this->translate("spares::index");

$this->translate("spares::edit");

$this->translate("spares::import");

$this->translate("shop-spares");

$this->translate("shop-spares::index");

$this->translate("shop-spares::cart");

$this->translate("shop-spares::add-car");

$this->translate("shop-spares::orders");

$this->translate("shop-spares::export-orders");

$this->translate("shop-spares::order-edit");

$this->translate("shop-spares::export-bespeak-order");

$this->translate("shop-spares::export-sending-order");

$this->translate("shop-spares::export-accept-order");

$this->translate("shop-spares::order-history");

$this->translate("shop-spares::order-mail-history");

$this->translate("shop-spares::take-work");

$this->translate("shop-spares::confirm-application");

$this->translate("shop-spares::checkout-delivery");

$this->translate("shop-spares::take-order");

$this->translate("cart");

$this->translate("cart::add-to-cart");

$this->translate("cart::remove-item");

$this->translate("logistics::photos");

$this->translate("logistics::download-one-archive");

$this->translate("shop-spares::delete-order");

$this->translate("promotional-products");

$this->translate("promotional-products::index");

$this->translate("promotional-products::add");

$this->translate("promotional-products::edit");

$this->translate("promotional-products::delete");

$this->translate("shop-promotional-products");

$this->translate("shop-promotional-products::index");

$this->translate("shop-promotional-products::cart");

$this->translate("shop-promotional-products::orders");

$this->translate("shop-promotional-products::export-orders");

$this->translate("shop-promotional-products::order-edit");

$this->translate("shop-promotional-products::order-history");

$this->translate("shop-promotional-products::order-mail-history");

$this->translate("shop-promotional-products::take-work");

$this->translate("shop-promotional-products::confirm-application");

$this->translate("shop-promotional-products::checkout-delivery");

$this->translate("shop-promotional-products::delete-order");

$this->translate("mon-fri");

$this->translate("satur");

$this->translate("sun");

$this->translate("city::export");

$this->translate("shop-promotional-products::download-file");

$this->translate("vidy-oplat::option-persent");

$this->translate("vidy-rassrochek::option-persent");

$this->translate("vidy-kreditov::option-persent");

$this->translate("vidy-lizinga::option-persent");

$this->translate("shop-promotional-products::application-rejected");

$this->translate("logistics::ajax-get-autocards");

$this->translate("type-autocarts");

$this->translate("type-autocarts::index");

$this->translate("type-autocarts::add");

$this->translate("type-autocarts::edit");

$this->translate("type-autocarts::delete");

$this->translate("autocarts-forwarder");

$this->translate("autocarts-forwarder::index");

$this->translate("autocarts-forwarder::add");

$this->translate("autocarts-forwarder::edit");

$this->translate("autocarts-forwarder::delete");

$this->translate("shop-spares::warranty");

$this->translate("soft-loans::index");

$this->translate("soft-loans::create");

$this->translate("soft-loans::edit");

$this->translate("soft-loans::delete");

$this->translate("soft-loans::export");

$this->translate("status::change-status");

$this->translate("spare");

$this->translate("spare::city-products");

$this->translate("productCity");

$this->translate("productCity::edit");

$this->translate("spare::products-city");

$this->translate("spare::product-city");

$this->translate("spare::edit-product-city");

$this->translate("status::add-permission-settings");

$this->translate("status::change");

$this->translate("invoice");

$this->translate("invoice::test");

$this->translate("shop-spare");

$this->translate("shop-spare::history");

$this->translate("invoice::sync");

$this->translate("invoice::view");

$this->translate("invoice::history");

$this->translate("AssetsBundle\Controller\Tools");

$this->translate("AssetsBundle\Controller\Tools::render-assets");

$this->translate("AssetsBundle\Controller\Tools::empty-cache");

$this->translate("agere\grid");

$this->translate("agere\grid::shop-spares-shop");

$this->translate("agere\grid::shop-spares-orders");

$this->translate("agere\grid::shop-spares-warranty");

$this->translate("agere\grid::soft-loans-modal-auto");

$this->translate("agere\grid::soft-loans-modal-buyers");

$this->translate("agere\grid::soft-loans");

$this->translate("handbook");

$this->translate("handbook::change-status");

$this->translate("buyers::list");

$this->translate("buyers::progress");

$this->translate("buyers::edit-old");

$this->translate("buyers::export");

$this->translate("buyers::import");

$this->translate("shop-spares::index111");

$this->translate("shop-spares::open-card");

$this->translate("shop-spares::check-cart-warranty-status");

$this->translate("shop-spares::get-redirect");

$this->translate("soft-loans");

$this->translate("soft-loans::transfer-role");

$this->translate("soft-loans::ajax-order-sale-id");

$this->translate("reports");

$this->translate("reports::index");

$this->translate("shop-spare::index");

$this->translate("shop-spare::warranty-edit");

$this->translate("shop-spare::cart");

$this->translate("shop-spare::add-car");

$this->translate("shop-spare::orders");

$this->translate("shop-spare::export-orders");

$this->translate("shop-spare::order-edit");

$this->translate("shop-spare::export-bespeak-order");

$this->translate("shop-spare::export-sending-order");

$this->translate("shop-spare::export-accept-order");

$this->translate("shop-spare::order-history");

$this->translate("shop-spare::order-mail-history");

$this->translate("shop-spare::open-card");

$this->translate("shop-spare::take-work");

$this->translate("shop-spare::sent-warehouse");

$this->translate("shop-spare::confirm-application");

$this->translate("shop-spare::checkout-delivery");

$this->translate("shop-spare::take-order");

$this->translate("shop-spare::delete-order");

$this->translate("shop-spare::get-redirect");

$this->translate("shop-spare::delete");

$this->translate("shop-spare::delete-lite");

$this->translate("invoice::edit");

$this->translate("invoice::invoice-products");

$this->translate("soap-api");

$this->translate("client");

$this->translate("soap-api::client");

$this->translate("client-product");

$this->translate("soap-api::client-product");

$this->translate("post");

$this->translate("soap-api::post");

$this->translate("soap-api::index");

$this->translate("index-new");

$this->translate("soap-api::index-new");

$this->translate("index-old");

$this->translate("soap-api::index-old");

$this->translate("importer");

$this->translate("import");

$this->translate("importer::import");

$this->translate("spare::index");

$this->translate("products");

$this->translate("spare::products");

$this->translate("orders");

$this->translate("spare::orders");

$this->translate("invoices");

$this->translate("spare::invoices");

$this->translate("product-city");

$this->translate("in-fact");

$this->translate("spare::in-fact");

$this->translate("view");

$this->translate("spare::view");

$this->translate("edit");

$this->translate("spare::edit");

$this->translate("edit-product-city");

$this->translate("delete");

$this->translate("spare::delete");

$this->translate("delete-lite");

$this->translate("spare::delete-lite");

$this->translate("ra-supplier");

$this->translate("ra-supplier::index");

$this->translate("create");

$this->translate("ra-supplier::create");

$this->translate("ra-supplier::edit");

$this->translate("ra-supplier::delete");

$this->translate("ra-supplier::delete-lite");

$this->translate("discount");

$this->translate("discount::index");

$this->translate("card");

$this->translate("discount::card");

$this->translate("discount::view");

$this->translate("discount::create");

$this->translate("discount::edit");

$this->translate("progress");

$this->translate("discount::progress");

$this->translate("buyer");

$this->translate("discount::buyer");

$this->translate("history");

$this->translate("discount::history");

$this->translate("discount::import");

$this->translate("discount::delete");

$this->translate("discount::delete-lite");

$this->translate("buyers::create");

$this->translate("buyer-progress");

$this->translate("buyer-progress::index");

$this->translate("buyer-progress::create");

$this->translate("buyer-progress::edit");

$this->translate("disable");

$this->translate("buyer-progress::disable");

$this->translate("buyer-progress::buyer");

$this->translate("buyer-progress::delete");

$this->translate("buyer-progress::delete-lite");

$this->translate("import-file");

$this->translate("store::import-file");

$this->translate("import-pko");

$this->translate("store::import-pko");

$this->translate("import-product-check");

$this->translate("store::import-product-check");

$this->translate("import-consignment");

$this->translate("store::import-consignment");

$this->translate("import-account-file");

$this->translate("store::import-account-file");

$this->translate("buyer::index");

$this->translate("list");

$this->translate("buyer::list");

$this->translate("info");

$this->translate("buyer::info");

$this->translate("buyer::progress");

$this->translate("buyer::create");

$this->translate("add");

$this->translate("buyer::add");

$this->translate("buyer::edit");

$this->translate("edit-old");

$this->translate("buyer::edit-old");

$this->translate("details");

$this->translate("buyer::details");

$this->translate("buyer::delete");

$this->translate("export");

$this->translate("buyer::export");

$this->translate("buyer::import");

$this->translate("checkout-view");

$this->translate("cart::checkout-view");

$this->translate("checkout");

$this->translate("cart::checkout");

$this->translate("selectedItems");

$this->translate("cart::selectedItems");

$this->translate("edit-item");

$this->translate("cart::edit-item");

$this->translate("import-lite");

$this->translate("importer::import-lite");

$this->translate("checkout-booking");

$this->translate("checkout-booking::list");

$this->translate("checkout-booking::progress");

$this->translate("checkout-booking::documents");

$this->translate("checkout-booking::delete");

$this->translate("checkout-booking::delete-lite");

$this->translate("order-edit");

$this->translate("spare::order-edit");

$this->translate("checkout-booking::index");

$this->translate("checkout-booking::cart");

$this->translate("checkout-booking::view");

$this->translate("manual-discount");

$this->translate("manual-discount::view");

$this->translate("doc");

$this->translate("invoice::doc");

$this->translate("invoice::edit-item");

$this->translate("data-grid");

$this->translate("data-grid::edit");

$this->translate("checkout-document");

$this->translate("checkout-document::index");

$this->translate("checkout-document::create");

$this->translate("download");

$this->translate("checkout-document::download");

$this->translate("close-day-cash");

$this->translate("checkout-document::close-day-cash");

$this->translate("checkout-document::checkout-document");

$this->translate("serial");

$this->translate("sync-quantity");

$this->translate("serial::sync-quantity");

$this->translate("select-data");

$this->translate("serial::select-data");

$this->translate("serial::delete");

$this->translate("serial::delete-lite");

$this->translate("common-documents");

$this->translate("checkout-document::common-documents");

$this->translate("validation");

$this->translate("permission::validation");

$this->translate("checkout-booking::validation");

$this->translate("try-to-synchronize");

$this->translate("checkout-document::try-to-synchronize");

$this->translate("handbook-item");

$this->translate("change-status");

$this->translate("handbook-item::change-status");

$this->translate("city::index-old");

$this->translate("city::create");

$this->translate("modify");

$this->translate("data-grid::modify");

$this->translate("invoice-product");

$this->translate("update-quantity");

$this->translate("invoice-product::update-quantity");

$this->translate("export-sales-report");

$this->translate("checkout-booking::export-sales-report");

$this->translate("buyer-progress::add");

$this->translate("buyer-progress::edit-old");

$this->translate("payments");

$this->translate("checkout-booking::payments");

$this->translate("checkout-authorized-person");

$this->translate("checkout-authorized-person::info");

$this->translate("checkout-authorized-person::list");

$this->translate("checkout-authorized-person::delete");

$this->translate("checkout-authorized-person::delete-lite");

$this->translate("close-day-cash-from-console");

$this->translate("checkout-document::close-day-cash-from-console");

$this->translate("store::documents");

$this->translate("permission-console");

$this->translate("prompt");

$this->translate("permission-console::prompt");

$this->translate("document");

$this->translate("document::index");

$this->translate("document::download");

$this->translate("authorized-persons::list");

$this->translate("authorized-persons::create");

$this->translate("issued");

$this->translate("store::issued");

$this->translate("admin");

$this->translate("dashboard");

$this->translate("admin::dashboard");

$this->translate("role");

$this->translate("role::edit");

$this->translate("update-urls");

$this->translate("role::create");

$this->translate("role::index");

$this->translate("question");

$this->translate("answer-log");

$this->translate("question::answer-log");

$this->translate("question::create");

$this->translate("question::edit");

$this->translate("question::index");

$this->translate("remove");

$this->translate("question::remove");

$this->translate("visitor");

$this->translate("visitor::index");

$this->translate("intuition");

$this->translate("intuition-log");

$this->translate("intuition::intuition-log");

$this->translate("complaint");

$this->translate("complaint::index");

$this->translate("complaint::view");

$this->translate("sys-config");

$this->translate("sys-config::edit");

$this->translate("user");

$this->translate("user::create");

$this->translate("user::dashboard");

$this->translate("user::edit");

$this->translate("user::index");

$this->translate("login");

$this->translate("user::login");

$this->translate("logout");

$this->translate("user::logout");

$this->translate("amazon");

$this->translate("bestseller-parse");

$this->translate("amazon::bestseller-parse");

$this->translate("better-parse");

$this->translate("amazon::better-parse");

$this->translate("marketplace");

$this->translate("amazon::marketplace");

$this->translate("name-parse");

$this->translate("amazon::name-parse");

$this->translate("price-parse");

$this->translate("amazon::price-parse");

$this->translate("sync-original");

$this->translate("amazon::sync-original");

$this->translate("admin-dashboard");

$this->translate("admin::admin-dashboard");

$this->translate("admin-edit");

$this->translate("sys-config::admin-edit");

$this->translate("admin-factory-modify-factory");

$this->translate("data-grid::admin-factory-modify-factory");

$this->translate("admin-modify");

$this->translate("data-grid::admin-modify");

$this->translate("admin-update-urls");

$this->translate("permission::admin-update-urls");

$this->translate("admin-create");

$this->translate("user::admin-create");

$this->translate("user::admin-dashboard");

$this->translate("user::admin-edit");

$this->translate("admin-index");

$this->translate("user::admin-index");

$this->translate("admin-login");

$this->translate("user::admin-login");

$this->translate("admin-logout");

$this->translate("user::admin-logout");

$this->translate("role::admin-create");

$this->translate("role::admin-edit");

$this->translate("role::admin-index");

$this->translate("admin-bestseller-parse");

$this->translate("amazon::admin-bestseller-parse");

$this->translate("admin-better-parse");

$this->translate("amazon::admin-better-parse");

$this->translate("admin-marketplace");

$this->translate("amazon::admin-marketplace");

$this->translate("admin-name-parse");

$this->translate("amazon::admin-name-parse");

$this->translate("admin-price-parse");

$this->translate("amazon::admin-price-parse");

$this->translate("admin-sync-original");

$this->translate("amazon::admin-sync-original");

$this->translate("amazon-dashboard");

$this->translate("dashboard-admin-factory-summary-factory");

$this->translate("amazon-dashboard::dashboard-admin-factory-summary-factory");

$this->translate("dashboard-admin-summary");

$this->translate("amazon-dashboard::dashboard-admin-summary");

$this->translate("product");

$this->translate("product-admin-competitor");

$this->translate("product::product-admin-competitor");

$this->translate("product-admin-index");

$this->translate("product::product-admin-index");

$this->translate("product-admin-product");

$this->translate("product::product-admin-product");

$this->translate("product-admin-view");

$this->translate("product::product-admin-view");

$this->translate("rank");

$this->translate("rank-admin-chart");

$this->translate("rank::rank-admin-chart");

$this->translate("rank-admin-competitor");

$this->translate("rank::rank-admin-competitor");

$this->translate("rank-admin-get-chart");

$this->translate("rank::rank-admin-get-chart");

$this->translate("rank-admin-history");

$this->translate("rank::rank-admin-history");

$this->translate("rank-admin-index");

$this->translate("rank::rank-admin-index");

$this->translate("rank-admin-our");

$this->translate("rank::rank-admin-our");

$this->translate("rank-admin-rank");

$this->translate("rank::rank-admin-rank");

$this->translate("rank-admin-track");

$this->translate("rank::rank-admin-track");

$this->translate("rank-admin-tracking");

$this->translate("rank::rank-admin-tracking");

$this->translate("rank-admin-update-profile-history");

$this->translate("rank::rank-admin-update-profile-history");

$this->translate("review");

$this->translate("review-admin-index");

$this->translate("review::review-admin-index");

$this->translate("admin-summary");

$this->translate("amazon-dashboard::admin-summary");

$this->translate("admin-competitor");

$this->translate("product::admin-competitor");

$this->translate("product::admin-index");

$this->translate("admin-product");

$this->translate("product::admin-product");

$this->translate("admin-view");

$this->translate("product::admin-view");

$this->translate("admin-chart");

$this->translate("rank::admin-chart");

$this->translate("rank::admin-competitor");

$this->translate("admin-get-chart");

$this->translate("rank::admin-get-chart");

$this->translate("admin-history");

$this->translate("rank::admin-history");

$this->translate("rank::admin-index");

$this->translate("admin-our");

$this->translate("rank::admin-our");

$this->translate("admin-rank");

$this->translate("rank::admin-rank");

$this->translate("admin-track");

$this->translate("rank::admin-track");

$this->translate("admin-tracking");

$this->translate("rank::admin-tracking");

$this->translate("admin-update-profile-history");

$this->translate("rank::admin-update-profile-history");

$this->translate("review::admin-index");

$this->translate("notification");

$this->translate("notification::admin-index");

$this->translate("admin-bestseller");

$this->translate("amazon::admin-bestseller");

$this->translate("admin-sync-original-parse");

$this->translate("amazon::admin-sync-original-parse");

$this->translate("dashboard::admin-index");

$this->translate("admin-top-rated");

$this->translate("dashboard::admin-top-rated");

$this->translate("admin-clean");

$this->translate("product::admin-clean");

$this->translate("admin-update-history-marketplace-product");

$this->translate("rank::admin-update-history-marketplace-product");

$this->translate("admin-data");

$this->translate("category::admin-data");

$this->translate("category::admin-index");

$this->translate("category::admin-modify");

$this->translate("customer");

$this->translate("customer::admin-index");

$this->translate("review::admin-summary");

$this->translate("order");

$this->translate("order::admin-index");

$this->translate("keyword");

$this->translate("keyword::admin-index");

$this->translate("admin-buttons");

$this->translate("data-grid::admin-buttons");

$this->translate("realty");

$this->translate("realty::admin-edit");

$this->translate("realty::admin-index");

$this->translate("admin-parse");

$this->translate("realty::admin-parse");

$this->translate("selection");

$this->translate("selection::admin-create");

$this->translate("selection::admin-index");